#!/bin/sh
# add calibration links to website home page

mkdir -p /var/www/mnt/local/sysconfig
sep='<br>'
for cf in /mnt/local/rc.user /mnt/local/sysconfig/* /tmp/u-boot_env
do
	hf=$cf
	[ $hf = ${hf%.*} ] && hf=$hf.txt
	sed -i /var/www/d-tacq/acq_home_page.html \
	-e"/LOCSET/i <a class=\"acqLink\" href=\"$hf\" onClick=\"return popup\(this, 'href_link'\)\">$cf</a>$sep"
done

<a class="acqLink" href="http://10.12.197.21:8080/" onClick="return popup(this, 'newone')">gpsmon</a><br>

SERVER=$(/usr/local/CARE/get-ip-address)
sed -i /var/www/d-tacq/acq_home_page.html \
 -e"/LOCSET/i <br><a class=\"acqLink\" href=\"http://${SERVER}:8235/\" onClick=\"return popup\(this, 'transient_state_monitor'\)\">transient_state_monitor</a><br>"

ttyd -p 8235 nc localhost 2235 2>&1 & 

mkdir -p /var/www/d-tacq/cal
for calfile in /dev/sites/?/caldef.xml
do
	[ -e $calfile ] || exit
	rp=${calfile%*/caldef.xml}
	site=$(basename $rp)
	ln -s $calfile /var/www/d-tacq/cal/site.$site.xml
	sed -i /var/www/d-tacq/acq_home_page.html \
	-e"/CALINS/i  <a class=\"acqLink\" href=\"./cal/site.$site.xml\" onClick=\"return popup\(this, 'href_link'\)\">site$site.xml</a> | "
done

