#!/bin/sh
# add calibration links to website home page

mkdir -p /var/www/mnt/local/sysconfig
sep='<br>'
for cf in /mnt/local/rc.user /mnt/local/sysconfig/* /tmp/u-boot_env
do
	hf=$cf
#	[ $hf = ${hf%.*} ] && hf=$hf.txt
	sed -i /var/www/d-tacq/acq_home_page.html \
	-e"/LOCSET/i <a class=\"acqLink\" href=\"$hf\" onClick=\"return popup\(this, 'href_link'\)\">$cf</a>$sep"
done

SERVER=$(/usr/local/CARE/get-ip-address)
sed -i /var/www/d-tacq/acq_home_page.html \
 -e"/LOCSET/i <p class=\"acqDetail\">Status Terminals : <a class=\"acqLink\" href=\"http://${SERVER}:8235/\" onClick=\"return popup\(this, 'transient_state_monitor'\)\">transient state monitor</a>"

ttyd -p 8235 nc localhost 2235 2>&1 & 

if [ -e /dev/acq400.0.knobs/wr_tai_cur ]; then
	sed -i /var/www/d-tacq/acq_home_page.html \
 -e"/LOCSET/i | <a class=\"acqLink\" href=\"/tty_wr\" onClick=\"return popup\(this, 'WR Console'\)\">WR Console</a>"
fi

sed -i /var/www/d-tacq/acq_home_page.html \
 -e"/LOCSET/i</p>"

mkdir -p /var/www/d-tacq/cal
for calfile in /dev/sites/?/caldef.xml
do
	[ -e $calfile ] || exit
	rp=${calfile%*/caldef.xml}
	site=$(basename $rp)
	ln -s $calfile /var/www/d-tacq/cal/site.$site.xml
	sed -i /var/www/d-tacq/acq_home_page.html \
	-e"/CALINS/i  <a class=\"acqLink\" href=\"./cal/site.$site.xml\" onClick=\"return popup\(this, 'href_link'\)\">site$site.xml</a> | "
done

